In [11]:
import numpy as np
mylist = [[1,2,3],[4,5,6]]
myarray = np.array(mylist)
print(myarray)


[[1 2 3]
 [4 5 6]]


Generating the random number

In [4]:
np.random.rand(2)

array([0.46211202, 0.71721003])

In [5]:
# generating the integers
np.random.randint(1,100)

83

In [ ]:
# seed also use for generating the same random number

In [13]:
# reshape the array
myarray.reshape(3,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [14]:
# find teh min number and max number
myarray.max()

6

In [15]:
myarray.min()

1

In [16]:
# checking the shape of the array
myarray.shape

(2, 3)

In [17]:
# checking the datatype
myarray.dtype

dtype('int64')

Numpy Indexing and Selection

In [18]:
arr = np.arange(0,11)

In [19]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [23]:
print("8th number(0-based indexing): ",arr[7]);

8th number(0-based indexing):  7


Broadcasting


In [24]:
arr[0:5] = 100
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [25]:
arr_2d = np.array([[5,10,15],[20,25,30]])
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30]])

In [26]:
arr_2d[0][0]

5

In [29]:
arr2d = arr_2d[0][0:3]
arr2d

array([ 5, 10, 15])

In [30]:
# Numpy operations
arr1 = [1,2,3]
arr2 = [4,5,6]

print(arr1+arr2)

[1, 2, 3, 4, 5, 6]


In [31]:
np.sqrt(arr1)

array([1.        , 1.41421356, 1.73205081])

In [32]:
np.exp(arr1)

array([ 2.71828183,  7.3890561 , 20.08553692])

In [33]:
np.log(arr1)

array([0.        , 0.69314718, 1.09861229])

In [34]:
np.sin(arr1)

array([0.84147098, 0.90929743, 0.14112001])

In [35]:
np.cos(arr1)

array([ 0.54030231, -0.41614684, -0.9899925 ])

In [36]:
arr1.sum()

AttributeError: ignored

In [37]:
arr1.mean()

AttributeError: ignored

In [ ]:
# do the sum in axis wise
arr_2d.sum()