In [ ]:
from scipy import constants

# constants is a module that have any constant value
---
constants.h--> 6.62607015e-34

constants.c--> 299792458.0

constants.pi--> 3.14..

constants.liter--> 0.001

---

**There are various constants:**

c: Speed of light in vacuum (in meters per second).

G: Gravitational constant (in meters^3 per kilogram per second^2).

hbar: Reduced Planck's constant (h divided by 2π, in Joule-seconds or meters squared kilograms per second).

h: Planck's constant (in Joule-seconds or meters squared kilograms per second).

e: Elementary charge (in Coulombs).

m_e: Electron mass (in kilograms).

m_p: Proton mass (in kilograms).

m_n: Neutron mass (in kilograms).

mu_0: Magnetic constant (permeability of vacuum) (in Henrys per meter).

epsilon_0: Electric constant (permittivity of vacuum) (in Farads per meter).

N_A: Avogadro's number (in particles per mole).

k: Boltzmann constant (in Joules per Kelvin).

R: Gas constant (in Joules per mole per Kelvin).

sigma: Stefan-Boltzmann constant (in Watts per meter squared per Kelvin^4).

atm: Standard atmosphere (in Pascals).

muB: Bohr magneton (in Joules per Tesla).

phi0: Magnetic flux quantum (in Weber).

Rydberg: Rydberg constant (in reciprocal meters).

eV: Electronvolt (in Joules).

alpha: Fine-structure constant (dimensionless).


In [ ]:
print(constants.liter)
print(constants.h)
print(constants.pi)
print(constants.c)

0.001
6.62607015e-34
3.141592653589793
299792458.0


we will see the units of constants using dir()


In [ ]:
print(dir(constants))

['Avogadro', 'Boltzmann', 'Btu', 'Btu_IT', 'Btu_th', 'ConstantWarning', 'G', 'Julian_year', 'N_A', 'Planck', 'R', 'Rydberg', 'Stefan_Boltzmann', 'Wien', '__all__', '__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__path__', '__spec__', '_codata', '_constants', '_obsolete_constants', 'acre', 'alpha', 'angstrom', 'arcmin', 'arcminute', 'arcsec', 'arcsecond', 'astronomical_unit', 'atm', 'atmosphere', 'atomic_mass', 'atto', 'au', 'bar', 'barrel', 'bbl', 'blob', 'c', 'calorie', 'calorie_IT', 'calorie_th', 'carat', 'centi', 'codata', 'constants', 'convert_temperature', 'day', 'deci', 'degree', 'degree_Fahrenheit', 'deka', 'dyn', 'dyne', 'e', 'eV', 'electron_mass', 'electron_volt', 'elementary_charge', 'epsilon_0', 'erg', 'exa', 'exbi', 'femto', 'fermi', 'find', 'fine_structure', 'fluid_ounce', 'fluid_ounce_US', 'fluid_ounce_imp', 'foot', 'g', 'gallon', 'gallon_US', 'gallon_imp', 'gas_constant', 'gibi', 'giga', 'golden', 'golden_ratio', 'grain', '

# Use of optimizer

**finding the Root of the equation**

In [ ]:
from scipy.optimize import root
from math import cos

def eqn(x):
  return x+cos(x)

myroot  = root(eqn,0)

print(myroot.x)

[-0.73908513]


# **Finding the Maxima and Minima**

method - name of the method to use.

**Legal values:**
    
    'CG'

    'BFGS':
    You specify the optimization method as 'BFGS', which stands for Broyden-Fletcher-Goldfarb-Shanno.
    It's an iterative optimization method used for unconstrained optimization problems

    'Newton-CG'

    'L-BFGS-B'

    'TNC'

    'COBYLA'

    'SLSQP'

In [ ]:
from scipy.optimize import minimize
def eqn(x):
  return x**2+x+2

mymin =  minimize(eqn,0,method='BFGS')

print(mymin.x)

[-0.50000001]


# **What is Sparse Data**
Sparse data is data that has mostly unused elements (elements that don't carry any information ).

It can be an array like this one:

[1, 0, 2, 0, 0, 3, 0, 0, 0, 0, 0, 0]

 **Sparse Data**: is a data set where most of the item values are zero.

**Dense Array:** is the opposite of a sparse array: most of the values are not zero.

SciPy has a module, scipy.sparse that provides functions to deal with sparse data.
---
There are primarily two types of sparse matrices that we use:

CSC - Compressed Sparse Column. For efficient arithmetic, fast column slicing.

CSR - Compressed Sparse Row. For fast row slicing, faster matrix vector products

In [ ]:
import numpy as np
from scipy.sparse import csr_matrix

arr = np.array([0, 0, 0, 0, 0, 1, 1, 0, 2])

print(csr_matrix(arr))

  (0, 5)	1
  (0, 6)	1
  (0, 8)	2


sparse Matrix methods:
---
1.Viewing stored data (not the zero items) with the data property:

In [ ]:
print(csr_matrix(arr).data)


[1 1 2]


2.Counting nonzeros with the count_nonzero() method:

In [ ]:
print(csr_matrix(arr).count_nonzero())

3


In [ ]:
mat = csr_matrix(arr)
mat.eliminate_zeros()
print(mat)

  (0, 5)	1
  (0, 6)	1
  (0, 8)	2


In [ ]:
mat.data

array([1, 1, 2])

# `Graph:`
connected_components function expects a sparse matrix as input.


In [ ]:
from scipy.sparse.csgraph import connected_components

arr = np.array([
  [0, 1, 2],
  [1, 0, 0],
  [2, 0, 0]
])

newarr = csr_matrix(arr)  #we have to converted into sparse matrix because connected_components take sparse matrix as input
print(newarr)
print(connected_components(newarr))

  (0, 1)	1
  (0, 2)	2
  (1, 0)	1
  (2, 0)	2
(1, array([0, 0, 0], dtype=int32))


# Dijkstra

**Use the dijkstra method to find the shortest path in a graph from one element to another.**

It takes following arguments:

return_predecessors: boolean (True to return whole path of traversal otherwise False).

indices: index of the element to return all paths from that element only.

limit: max weight of path.

In [ ]:
from scipy.sparse.csgraph import dijkstra

print(dijkstra(newarr,return_predecessors=True,indices = 0))


(array([0., 1., 2.]), array([-9999,     0,     0], dtype=int32))


Finding the depth first search

In [ ]:
from scipy.sparse.csgraph import depth_first_order
arr = np.array([
  [0, 1, 0, 1],
  [1, 1, 1, 1],
  [2, 1, 1, 0],
  [0, 1, 0, 1]
])


newarr = csr_matrix(arr)

print(depth_first_order(newarr,1))  # 1 is the starting element of  traversing the whole graph


(array([1, 0, 3, 2], dtype=int32), array([    1, -9999,     1,     0], dtype=int32))


Breadth first order

In [ ]:
from scipy.sparse.csgraph import breadth_first_order
print(breadth_first_order(newarr,1))

(array([1, 0, 2, 3], dtype=int32), array([    1, -9999,     1,     1], dtype=int32))


# Spatial data

Spatial data refers to data that is represented in a geometric space.

E.g. points on a coordinate system.

We deal with spatial data problems on many tasks.

E.g. finding if a point is inside a boundary or not.

SciPy provides us with the module scipy.spatial, which has functions for working with spatial data.