In [2]:
import tensorflow as tf


There are different Types of tensors:
zero dim , one dim, two dim, three dim

In [ ]:
# Zerp dimensional tensor
tensor_zero_d = tf.constant(4)
print(tensor_zero_d)


tf.Tensor(4, shape=(), dtype=int32)


In [ ]:
# One dimensional tensor
tensor_one_d = tf.constant([1,2,3])
print(tensor_one_d)


tf.Tensor([1 2 3], shape=(3,), dtype=int32)


In [ ]:
# Two dimensional tensor
tensor_two_d = tf.constant([[1,2,3],[4,5,6]])
print(tensor_two_d)

tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)


In [ ]:
# Three dimensional tensor
tensor_three_d = tf.constant([[[1,2,3],[4,5,6]],[[11,22,33],[44,55,66]]])
print(tensor_three_d)

tf.Tensor(
[[[ 1  2  3]
  [ 4  5  6]]

 [[11 22 33]
  [44 55 66]]], shape=(2, 2, 3), dtype=int32)


In [ ]:
# To obtain tensor shape
# we use .shape()
print(tensor_three_d.shape)


(2, 2, 3)


In [ ]:
# finding the what is the type of tensor whether it is 1d,2d,3d
# we use .ndim
print(tensor_three_d.ndim)

3


In [ ]:
# four dimensional tensor
tensor_4_d = tf.constant([[[[1,2,3],[4,5,6]]],[[[11,22,33],[44,55,66]]],[[[1,2,3],[4,5,6]]],[[[11,22,33],[44,55,66]]]])
print(tensor_4_d)

tf.Tensor(
[[[[ 1  2  3]
   [ 4  5  6]]]


 [[[11 22 33]
   [44 55 66]]]


 [[[ 1  2  3]
   [ 4  5  6]]]


 [[[11 22 33]
   [44 55 66]]]], shape=(4, 1, 2, 3), dtype=int32)


In [ ]:
  # for allocating less memory , we use dtype = tf.intx
  # when we have memory constainst
  tensor_2_d = tf.constant([[1,2],[2,3]],dtype = tf.int16)
  print(tensor_2_d)

tf.Tensor(
[[1 2]
 [2 3]], shape=(2, 2), dtype=int16)


In [ ]:
# changing the dtype of any type of tensor
# we use .cast
casted_tensor = tf.cast(tensor_2_d,dtype = tf.bool)
print(casted_tensor)

tf.Tensor(
[[ True  True]
 [ True  True]], shape=(2, 2), dtype=bool)


In [ ]:
# we also tensor string
tensor_1_d_string = tf.constant(["hello world"])
print(tensor_1_d_string)

tf.Tensor([b'hello world'], shape=(1,), dtype=string)


In [ ]:
 TwoDim_string = tf.constant([["hello world"],["hi am i"]])
 print(TwoDim_string)

tf.Tensor(
[[b'hello world']
 [b'hi am i']], shape=(2, 1), dtype=string)


In [ ]:
# Convert numpy arry to tensor_method
import numpy as np
arr = np.array([1,2,3])
# print(arr)
# Now convert the array to tensor
tensor_convertor = tf.convert_to_tensor(arr)
print(tensor_convertor)

tf.Tensor([1 2 3], shape=(3,), dtype=int64)


In [ ]:
# eye method
# In eye method simple brackets are used for opening and closing
eye_tensor = tf.eye(
    3,  #when we assign no of rows = 3 then
    num_columns=None, # no of columns automatically 3
    batch_shape=None,
    dtype=tf.dtypes.float32,
    name=None
)

print(eye_tensor)

print('identical martrix * 3 : ')
print('')
print(3*eye_tensor)

tf.Tensor(
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]], shape=(3, 3), dtype=float32)
identical martrix * 3 : 

tf.Tensor(
[[3. 0. 0.]
 [0. 3. 0.]
 [0. 0. 3.]], shape=(3, 3), dtype=float32)


In [ ]:
Another_eye_tensor = tf.eye(
    num_rows=5,
    num_columns=None,
    batch_shape=[2,],
    dtype = tf.dtypes.int16,
    name = None
)

print(Another_eye_tensor)

tf.Tensor(
[[[1 0 0 0 0]
  [0 1 0 0 0]
  [0 0 1 0 0]
  [0 0 0 1 0]
  [0 0 0 0 1]]

 [[1 0 0 0 0]
  [0 1 0 0 0]
  [0 0 1 0 0]
  [0 0 0 1 0]
  [0 0 0 0 1]]], shape=(2, 5, 5), dtype=int16)


In [ ]:
# if we use number of columns which is not  same as num of rows
# then 1 is appear until the no of columns = no of rows
eye_tensor_not = tf.eye(
    num_rows = 5,
    num_columns = 3,
    batch_shape=None,
    dtype = tf.dtypes.int32,
    name = None
)

print(eye_tensor_not)

tf.Tensor(
[[1 0 0]
 [0 1 0]
 [0 0 1]
 [0 0 0]
 [0 0 0]], shape=(5, 3), dtype=int32)


In [ ]:
# filling with scaler value
scalerTensor = tf.fill(
    [3,3],5,
    #first we specify dimensions then a value to be filled with dimesions
    #in this [2,3] first we specify no of rows and 3 which means 3 columns
    # the value to be fill is 5
    name = None
)

print(scalerTensor)


# In the advancement of this we have ones method
one_tensor = tf.ones(
    [2,3],
    dtype = tf.dtypes.int32,
    name = None
)
print('\nthis is one tensor')
print(one_tensor)

# if we make all elements to be zeroes then:
zero_tensor = tf.zeros(
    [3,3]
)

print(zero_tensor)

tf.Tensor(
[[5 5 5]
 [5 5 5]
 [5 5 5]], shape=(3, 3), dtype=int32)

this is one tensor
tf.Tensor(
[[1 1 1]
 [1 1 1]], shape=(2, 3), dtype=int32)
tf.Tensor(
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]], shape=(3, 3), dtype=float32)


In [ ]:
# one_likeTensor = tf.ones_like(
#     scalerTensor
#     # name=None,
#     # dtype = tf.dtypes.int32
# )
one_likeTensor = tf.ones_like(scalerTensor)

print(one_likeTensor)



tf.Tensor(
[[1 1 1]
 [1 1 1]
 [1 1 1]], shape=(3, 3), dtype=int32)


In [ ]:
#  finding the rank
tf.rank(scalerTensor)
#  print(Rank_tensor)
# we can find the rank of any dimension of tensor
# output as numpy  = 2

#calculate the size of the tensor matrix i.e the number of elements
print("The size is:")
tf.size(scalerTensor)

The size is:


<tf.Tensor: shape=(), dtype=int32, numpy=9>

In [ ]:
# Creating the random tensor
Random_tensor = tf.random.normal(
    [3,3],
    mean = 100,
    stddev=1.0,
    dtype=tf.dtypes.float32,
    seed=None,
    name=None
)

print(Random_tensor)

print("This is the uniform tensor")
Uniform_tensor = tf.random.uniform(
    [3,3]
    # minval =0,
    # maxval = 8,
    # dtype = tf.dtypes.int32,  #if we use int32 then we must specify max value
    # seed = None,
    # name=None
)
print(Uniform_tensor)

# we use seed value so that when we call same random matrix with the same value

tf.Tensor(
[[ 99.53605   98.24807   99.695564]
 [ 99.71901  101.338196 100.82986 ]
 [ 98.63597   99.39357  101.0911  ]], shape=(3, 3), dtype=float32)
This is the uniform tensor
tf.Tensor(
[[0.6388838  0.998229   0.7037127 ]
 [0.42656648 0.6553192  0.17408562]
 [0.7433574  0.81673396 0.197168  ]], shape=(3, 3), dtype=float32)


In [ ]:
# Tensor indexed

In [ ]:
tensor_indexed = tf.constant([3,6,2,4,7,8])
print(tensor_indexed[0])
print(tensor_indexed[1:4])
print(tensor_indexed[0:4])
print(tensor_indexed[0:])

tf.Tensor(3, shape=(), dtype=int32)
tf.Tensor([6 2 4], shape=(3,), dtype=int32)
tf.Tensor([3 6 2 4], shape=(4,), dtype=int32)
tf.Tensor([3 6 2 4 7 8], shape=(6,), dtype=int32)


In [ ]:
 # we use range to print the number from initial to final-1
# range(initial,final)
print(tf.range(0,4))
# print(tf.range(0,))

tf.Tensor([0 1 2 3], shape=(4,), dtype=int32)


In [ ]:
# Creating two dimensional tensor
tensor_2d = tf.constant(
    [
        [1,2,3],
        [4,5,6],
        [7,8,9]
    ]
)
print(tensor_2d)

# now we print first 2 columns of each row
print(tensor_2d[0:3,0:2])
# i = 0
# for i in range(0,3):
#   print(tensor_2d[i,0:2])


tf.Tensor(
[[1 2 3]
 [4 5 6]
 [7 8 9]], shape=(3, 3), dtype=int32)
tf.Tensor(
[[1 2]
 [4 5]
 [7 8]], shape=(3, 2), dtype=int32)


In [4]:
# mathmatical operations
# absolute method
tensor_ = tf.constant([[-1,2,3],[-4,-6,5]])
print('before absolute : the tensor :')
print(tensor_)
print('')
print('after the absolute function: ')
abs_tensor = tf.abs(tensor_)
print(abs_tensor)

before absolute : the tensor :
tf.Tensor(
[[-1  2  3]
 [-4 -6  5]], shape=(2, 3), dtype=int32)
after the absolute function: 
tf.Tensor(
[[1 2 3]
 [4 6 5]], shape=(2, 3), dtype=int32)


In [7]:
sqrt_tensor = tf.sqrt((2.25)**2 + (4.75)**2)
print(sqrt_tensor)

tf.Tensor(5.255949, shape=(), dtype=float32)


In [10]:
# adding the tensor
tensor_1 = tf.constant([1,2,3])
tensor_2 = tf.constant([4,5,6])

add_tensor = tf.add(tensor_1,tensor_2)
print(add_tensor)

tf.Tensor([5 7 9], shape=(3,), dtype=int32)


In [11]:
print(tf.multiply(tensor_1,tensor_2))
print(tf.divide(tensor_1,tensor_2))

tf.Tensor([ 4 10 18], shape=(3,), dtype=int32)
tf.Tensor([0.25 0.4  0.5 ], shape=(3,), dtype=float64)


In [18]:
# using math library
# after adding .math into the existing statement
# the smaller tensor will stretched out to become the shape of bigger tensor
# i.e tf.constant([7]) is added to the tensor_1(which is the bigger tensor)
# for adding, we know that shape should be same
# so, tf.constant([7]) is going to streched out with the same element in repeated way to become the shape of tensor_1
# so In backend , after stretching  the tf.constant([7])--> [7,7,7]
# then it will be add
# we can print shape of the second tensor
print('the shape of first tensor then add')
print(tf.constant([7]).shape)
print("the tensor_1 is :")
print(tensor_1)
print('')
print('after adding:')
print(tf.math.add(tf.constant([7]),tensor_1))

the shape of first tensor then add
(1,)
the tensor_1 is :
tf.Tensor([1 2 3], shape=(3,), dtype=int32)

after adding:
tf.Tensor([ 8  9 10], shape=(3,), dtype=int32)


In [20]:
#now lets take another example
x_1 = tf.constant([[5,3,6,6,4,6]])
x_2 = tf.constant([[7],[5],[3]])
# it is element by element multiplication, not a matrix
print(tf.math.multiply(x_1,x_2))

tf.Tensor(
[[35 21 42 42 28 42]
 [25 15 30 30 20 30]
 [15  9 18 18 12 18]], shape=(3, 6), dtype=int32)


In [25]:
#  returns the max of two tensors
print('the maximum of two tensors:')
print(tf.math.maximum(tensor_1,tensor_2))
print('the minimum of two tensors')
print(tf.math.minimum(tensor_1,tensor_2))


the maximum of two tensors:
tf.Tensor([4 5 6], shape=(3,), dtype=int32)
the minimum of two tensors
tf.Tensor([1 2 3], shape=(3,), dtype=int32)


In [27]:
# we find the index of the maximum value using argmax
print(tf.math.argmax(tf.constant([100,2,3])))

tf.Tensor(0, shape=(), dtype=int64)


In [30]:
# we can find the index of maximum value of each column of 2d tensor using argmax
# In column , we set the axis  = 0
print(tf.math.argmax(tf.constant([[1,2,3],[4,5,6],[7,8,9]])),0)
# if we find the index with respect to row, we set the axis =1
print(tf.math.argmax(tf.constant([[1,2,3],[4,5,6],[7,8,9]])),1)
# we use reduce_min or reduce_max for finding the minimum and max of whole tensor, explore it!



tf.Tensor([2 2 2], shape=(3,), dtype=int64) 0
tf.Tensor([2 2 2], shape=(3,), dtype=int64) 1
